// This file is generated by rust-protobuf 3.5.1. Do not edit
// .proto file is parsed by protoc --rust_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `livetrace.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_5_1;

// @@protoc_insertion_point(message:livetrace.Ustack)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Ustack {
    // message oneof groups
    pub stack: ::std::option::Option<ustack::Stack>,
    // special fields
    // @@protoc_insertion_point(special_field:livetrace.Ustack.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Ustack {
    fn default() -> &'a Ustack {
        <Ustack as ::protobuf::Message>::default_instance()
    }
}

impl Ustack {
    pub fn new() -> Ustack {
        ::std::default::Default::default()
    }

    // uint64 addr = 1;

    pub fn addr(&self) -> u64 {
        match self.stack {
            ::std::option::Option::Some(ustack::Stack::Addr(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_addr(&mut self) {
        self.stack = ::std::option::Option::None;
    }

    pub fn has_addr(&self) -> bool {
        match self.stack {
            ::std::option::Option::Some(ustack::Stack::Addr(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_addr(&mut self, v: u64) {
        self.stack = ::std::option::Option::Some(ustack::Stack::Addr(v))
    }

    // string symbol = 2;

    pub fn symbol(&self) -> &str {
        match self.stack {
            ::std::option::Option::Some(ustack::Stack::Symbol(ref v)) => v,
            _ => "",
        }
    }

    pub fn clear_symbol(&mut self) {
        self.stack = ::std::option::Option::None;
    }

    pub fn has_symbol(&self) -> bool {
        match self.stack {
            ::std::option::Option::Some(ustack::Stack::Symbol(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_symbol(&mut self, v: ::std::string::String) {
        self.stack = ::std::option::Option::Some(ustack::Stack::Symbol(v))
    }

    // Mutable pointer to the field.
    pub fn mut_symbol(&mut self) -> &mut ::std::string::String {
        if let ::std::option::Option::Some(ustack::Stack::Symbol(_)) = self.stack {
        } else {
            self.stack = ::std::option::Option::Some(ustack::Stack::Symbol(::std::string::String::new()));
        }
        match self.stack {
            ::std::option::Option::Some(ustack::Stack::Symbol(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_symbol(&mut self) -> ::std::string::String {
        if self.has_symbol() {
            match self.stack.take() {
                ::std::option::Option::Some(ustack::Stack::Symbol(v)) => v,
                _ => panic!(),
            }
        } else {
            ::std::string::String::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "addr",
            Ustack::has_addr,
            Ustack::addr,
            Ustack::set_addr,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_deref_has_get_set_simpler_accessor::<_, _>(
            "symbol",
            Ustack::has_symbol,
            Ustack::symbol,
            Ustack::set_symbol,
        ));
        oneofs.push(ustack::Stack::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Ustack>(
            "Ustack",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Ustack {
    const NAME: &'static str = "Ustack";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.stack = ::std::option::Option::Some(ustack::Stack::Addr(is.read_uint64()?));
                },
                18 => {
                    self.stack = ::std::option::Option::Some(ustack::Stack::Symbol(is.read_string()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.stack {
            match v {
                &ustack::Stack::Addr(v) => {
                    my_size += ::protobuf::rt::uint64_size(1, v);
                },
                &ustack::Stack::Symbol(ref v) => {
                    my_size += ::protobuf::rt::string_size(2, &v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.stack {
            match v {
                &ustack::Stack::Addr(v) => {
                    os.write_uint64(1, v)?;
                },
                &ustack::Stack::Symbol(ref v) => {
                    os.write_string(2, v)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Ustack {
        Ustack::new()
    }

    fn clear(&mut self) {
        self.stack = ::std::option::Option::None;
        self.stack = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Ustack {
        static instance: Ustack = Ustack {
            stack: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Ustack {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Ustack").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Ustack {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Ustack {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `Ustack`
pub mod ustack {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:livetrace.Ustack.stack)
    pub enum Stack {
        // @@protoc_insertion_point(oneof_field:livetrace.Ustack.addr)
        Addr(u64),
        // @@protoc_insertion_point(oneof_field:livetrace.Ustack.symbol)
        Symbol(::std::string::String),
    }

    impl ::protobuf::Oneof for Stack {
    }

    impl ::protobuf::OneofFull for Stack {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::Ustack as ::protobuf::MessageFull>::descriptor().oneof_by_name("stack").unwrap()).clone()
        }
    }

    impl Stack {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Stack>("stack")
        }
    }
}

// @@protoc_insertion_point(message:livetrace.LivetraceCell)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct LivetraceCell {
    // message fields
    // @@protoc_insertion_point(field:livetrace.LivetraceCell.pid)
    pub pid: u32,
    // @@protoc_insertion_point(field:livetrace.LivetraceCell.samples)
    pub samples: u32,
    // @@protoc_insertion_point(field:livetrace.LivetraceCell.kstack)
    pub kstack: ::std::vec::Vec<u64>,
    // @@protoc_insertion_point(field:livetrace.LivetraceCell.ustack)
    pub ustack: ::std::vec::Vec<Ustack>,
    // special fields
    // @@protoc_insertion_point(special_field:livetrace.LivetraceCell.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LivetraceCell {
    fn default() -> &'a LivetraceCell {
        <LivetraceCell as ::protobuf::Message>::default_instance()
    }
}

impl LivetraceCell {
    pub fn new() -> LivetraceCell {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "pid",
            |m: &LivetraceCell| { &m.pid },
            |m: &mut LivetraceCell| { &mut m.pid },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "samples",
            |m: &LivetraceCell| { &m.samples },
            |m: &mut LivetraceCell| { &mut m.samples },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "kstack",
            |m: &LivetraceCell| { &m.kstack },
            |m: &mut LivetraceCell| { &mut m.kstack },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "ustack",
            |m: &LivetraceCell| { &m.ustack },
            |m: &mut LivetraceCell| { &mut m.ustack },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LivetraceCell>(
            "LivetraceCell",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LivetraceCell {
    const NAME: &'static str = "LivetraceCell";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.pid = is.read_uint32()?;
                },
                16 => {
                    self.samples = is.read_uint32()?;
                },
                26 => {
                    is.read_repeated_packed_uint64_into(&mut self.kstack)?;
                },
                24 => {
                    self.kstack.push(is.read_uint64()?);
                },
                34 => {
                    self.ustack.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.pid != 0 {
            my_size += ::protobuf::rt::uint32_size(1, self.pid);
        }
        if self.samples != 0 {
            my_size += ::protobuf::rt::uint32_size(2, self.samples);
        }
        my_size += ::protobuf::rt::vec_packed_uint64_size(3, &self.kstack);
        for value in &self.ustack {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.pid != 0 {
            os.write_uint32(1, self.pid)?;
        }
        if self.samples != 0 {
            os.write_uint32(2, self.samples)?;
        }
        os.write_repeated_packed_uint64(3, &self.kstack)?;
        for v in &self.ustack {
            ::protobuf::rt::write_message_field_with_cached_size(4, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LivetraceCell {
        LivetraceCell::new()
    }

    fn clear(&mut self) {
        self.pid = 0;
        self.samples = 0;
        self.kstack.clear();
        self.ustack.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LivetraceCell {
        static instance: LivetraceCell = LivetraceCell {
            pid: 0,
            samples: 0,
            kstack: ::std::vec::Vec::new(),
            ustack: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LivetraceCell {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LivetraceCell").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LivetraceCell {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LivetraceCell {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:livetrace.LivetraceList)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct LivetraceList {
    // message fields
    // @@protoc_insertion_point(field:livetrace.LivetraceList.list)
    pub list: ::std::vec::Vec<LivetraceCell>,
    // special fields
    // @@protoc_insertion_point(special_field:livetrace.LivetraceList.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LivetraceList {
    fn default() -> &'a LivetraceList {
        <LivetraceList as ::protobuf::Message>::default_instance()
    }
}

impl LivetraceList {
    pub fn new() -> LivetraceList {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "list",
            |m: &LivetraceList| { &m.list },
            |m: &mut LivetraceList| { &mut m.list },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LivetraceList>(
            "LivetraceList",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LivetraceList {
    const NAME: &'static str = "LivetraceList";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.list.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.list {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.list {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LivetraceList {
        LivetraceList::new()
    }

    fn clear(&mut self) {
        self.list.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LivetraceList {
        static instance: LivetraceList = LivetraceList {
            list: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LivetraceList {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LivetraceList").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LivetraceList {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LivetraceList {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0flivetrace.proto\x12\tlivetrace\"A\n\x06Ustack\x12\x14\n\x04addr\
    \x18\x01\x20\x01(\x04H\0R\x04addr\x12\x18\n\x06symbol\x18\x02\x20\x01(\t\
    H\0R\x06symbolB\x07\n\x05stack\"~\n\rLivetraceCell\x12\x10\n\x03pid\x18\
    \x01\x20\x01(\rR\x03pid\x12\x18\n\x07samples\x18\x02\x20\x01(\rR\x07samp\
    les\x12\x16\n\x06kstack\x18\x03\x20\x03(\x04R\x06kstack\x12)\n\x06ustack\
    \x18\x04\x20\x03(\x0b2\x11.livetrace.UstackR\x06ustack\"=\n\rLivetraceLi\
    st\x12,\n\x04list\x18\x01\x20\x03(\x0b2\x18.livetrace.LivetraceCellR\x04\
    listJ\xd5\x04\n\x06\x12\x04\0\0\x15\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\
    \n\x08\n\x01\x02\x12\x03\x01\0\x12\n\n\n\x02\x04\0\x12\x04\x03\0\x08\x01\
    \n\n\n\x03\x04\0\x01\x12\x03\x03\x08\x0e\n\x0c\n\x04\x04\0\x08\0\x12\x04\
    \x04\x04\x07\x05\n\x0c\n\x05\x04\0\x08\0\x01\x12\x03\x04\n\x0f\n\x0b\n\
    \x04\x04\0\x02\0\x12\x03\x05\x08\x18\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\
    \x05\x08\x0e\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x05\x0f\x13\n\x0c\n\x05\
    \x04\0\x02\0\x03\x12\x03\x05\x16\x17\n\x0b\n\x04\x04\0\x02\x01\x12\x03\
    \x06\x08\x1a\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x06\x08\x0e\n\x0c\n\
    \x05\x04\0\x02\x01\x01\x12\x03\x06\x0f\x15\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03\x06\x18\x19\n\n\n\x02\x04\x01\x12\x04\n\0\x10\x01\n\n\n\x03\x04\
    \x01\x01\x12\x03\n\x08\x15\n\x14\n\x04\x04\x01\x02\0\x12\x03\x0c\x04\x13\
    \"\x07\x20\x20pid\x20\n\n\x0c\n\x05\x04\x01\x02\0\x05\x12\x03\x0c\x04\n\
    \n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x0c\x0b\x0e\n\x0c\n\x05\x04\x01\
    \x02\0\x03\x12\x03\x0c\x11\x12\n\x19\n\x04\x04\x01\x02\x01\x12\x03\r\x04\
    \x17\"\x0c\x20\x20\xe6\xa0\xb7\xe6\x9c\xac\xe6\x95\xb0\n\n\x0c\n\x05\x04\
    \x01\x02\x01\x05\x12\x03\r\x04\n\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\
    \r\x0b\x12\n\x0c\n\x05\x04\x01\x02\x01\x03\x12\x03\r\x15\x16\n\x1e\n\x04\
    \x04\x01\x02\x02\x12\x03\x0e\x04\x1f\"\x11\x20\xe5\x86\x85\xe6\xa0\xb8\
    \xe6\x80\x81\xe7\xac\xa6\xe5\x8f\xb7\n\n\x0c\n\x05\x04\x01\x02\x02\x04\
    \x12\x03\x0e\x04\x0c\n\x0c\n\x05\x04\x01\x02\x02\x05\x12\x03\x0e\r\x13\n\
    \x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\x0e\x14\x1a\n\x0c\n\x05\x04\x01\
    \x02\x02\x03\x12\x03\x0e\x1d\x1e\n\x0b\n\x04\x04\x01\x02\x03\x12\x03\x0f\
    \x04\x1f\n\x0c\n\x05\x04\x01\x02\x03\x04\x12\x03\x0f\x04\x0c\n\x0c\n\x05\
    \x04\x01\x02\x03\x06\x12\x03\x0f\r\x13\n\x0c\n\x05\x04\x01\x02\x03\x01\
    \x12\x03\x0f\x14\x1a\n\x0c\n\x05\x04\x01\x02\x03\x03\x12\x03\x0f\x1d\x1e\
    \n\n\n\x02\x04\x02\x12\x04\x12\0\x15\x01\n\n\n\x03\x04\x02\x01\x12\x03\
    \x12\x08\x15\n\x0b\n\x04\x04\x02\x02\0\x12\x03\x14\x04$\n\x0c\n\x05\x04\
    \x02\x02\0\x04\x12\x03\x14\x04\x0c\n\x0c\n\x05\x04\x02\x02\0\x06\x12\x03\
    \x14\r\x1a\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03\x14\x1b\x1f\n\x0c\n\x05\
    \x04\x02\x02\0\x03\x12\x03\x14\"#b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(Ustack::generated_message_descriptor_data());
            messages.push(LivetraceCell::generated_message_descriptor_data());
            messages.push(LivetraceList::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
