#!/bin/sh
set -e

YCOMP="$0"
while [ -L "$YCOMP" ]; do
	LINK="$(readlink "$YCOMP")"
	case "$LINK" in
		/*) YCOMP="$LINK";;
		*)  YCOMP="${YCOMP%/*}/$LINK";;
	esac
done

java -Xmx512m -jar "${YCOMP%/*}/yComp.jar" "$@"
